import type { Newsletter } from "../src/lib/tipos.ts";

/**
 * GERADO por `npm run importar` a partir da folha "Horário" do Excel.
 *
 * Não editar as periodicidades nem as horas à mão — mexer no Excel e voltar a
 * correr o importador. Os campos `remetentes` e `padraoAssunto` são a
 * exceção: não estão no Excel, escrevem-se aqui e o importador preserva-os.
 *
 * 62 newsletters, 48 ativas.
 */
export const NEWSLETTERS: Newsletter[] = [
  // Automática
  {
    id: "cm-exclusivos",
    marca: "CM",
    nome: "Exclusivos",
    periodicidade: "diaria",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "06:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Automático
  {
    id: "negocios-primeira-pagina",
    marca: "Negócios",
    nome: "Primeira Página",
    periodicidade: "dias_uteis",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "06:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "record-premium",
    marca: "Record",
    nome: "Premium",
    periodicidade: "diaria",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "07:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "flash-weekend",
    marca: "Flash",
    nome: "Weekend",
    periodicidade: "dia_semana",
    diasSemana: [4],
    diasMes: null,
    horaPrevista: "07:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "negocios-5-coisas",
    marca: "Negócios",
    nome: "5 Coisas",
    periodicidade: "dias_uteis",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "08:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "sabado-capa",
    marca: "Sábado",
    nome: "Capa",
    periodicidade: "dia_semana",
    diasSemana: [4],
    diasMes: null,
    horaPrevista: "08:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "flash-mundo",
    marca: "Flash",
    nome: "Mundo",
    periodicidade: "diaria",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "08:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "record-geral",
    marca: "Record",
    nome: "Geral",
    periodicidade: "diaria",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "09:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "negocios-assinantes-diaria",
    marca: "Negócios",
    nome: "Assinantes Diária",
    periodicidade: "dias_uteis",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "09:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "maxima-geral",
    marca: "Máxima",
    nome: "Geral",
    periodicidade: "dias_uteis",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "09:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "sabado-a-sabado-e-todos-os-dias",
    marca: "Sábado",
    nome: "A SÁBADO É TODOS OS DIAS",
    periodicidade: "dias_uteis",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "09:30",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "record-premium-plus",
    marca: "Record",
    nome: "Premium Plus",
    periodicidade: "diaria",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "09:30",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "record-euro-2020",
    marca: "Record",
    nome: "Euro 2020",
    periodicidade: "diaria",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "09:30",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: false,
  },
  // Gerido
  {
    id: "negocios-premium-morning-call",
    marca: "Negócios",
    nome: "Premium Morning Call",
    periodicidade: "dias_uteis",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "09:47",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "negocios-premium-plus-morning-call",
    marca: "Negócios",
    nome: "Premium Plus Morning Call",
    periodicidade: "dias_uteis",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "09:47",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Automática
  {
    id: "cm-bom-dia",
    marca: "CM",
    nome: "Bom Dia",
    periodicidade: "diaria",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "10:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "record-o-melhor-da-semana",
    marca: "Record",
    nome: "O Melhor da Semana",
    periodicidade: "dia_semana",
    diasSemana: [5],
    diasMes: null,
    horaPrevista: "10:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "flash-bom-dia",
    marca: "Flash",
    nome: "Bom Dia",
    periodicidade: "diaria",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "10:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Automátivo
  {
    id: "vidas-geral",
    marca: "Vidas",
    nome: "Geral",
    periodicidade: "diaria",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "10:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "record-mercado-de-transferencias",
    marca: "Record",
    nome: "Mercado de Transferências",
    periodicidade: "diaria",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "10:30",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Automático
  {
    id: "negocios-dow-jones-mercados-globais",
    marca: "Negócios",
    nome: "Dow Jones - Mercados Globais",
    periodicidade: "dias_uteis",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "10:30",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: false,
  },
  // Automático
  {
    id: "sabado-edicao-manha",
    marca: "Sábado",
    nome: "Edição Manhã",
    periodicidade: "diaria",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "10:30",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Automático
  {
    id: "negocios-abertura",
    marca: "Negócios",
    nome: "Abertura",
    periodicidade: "dias_uteis",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "10:30",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "record-sporting",
    marca: "Record",
    nome: "Sporting",
    periodicidade: "diaria",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "11:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "record-porto",
    marca: "Record",
    nome: "Porto",
    periodicidade: "diaria",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "11:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Automático
  {
    id: "negocios-financas",
    marca: "Negócios",
    nome: "Finanças",
    periodicidade: "dia_semana",
    diasSemana: [2],
    diasMes: null,
    horaPrevista: "11:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "negocios-radar-verde",
    marca: "Negócios",
    nome: "Radar Verde",
    periodicidade: "dia_semana",
    diasSemana: [3],
    diasMes: null,
    horaPrevista: "11:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: false,
  },
  // Gerido
  {
    id: "negocios-opiniao-economistas",
    marca: "Negócios",
    nome: "Opinião Economistas",
    periodicidade: "dia_semana",
    diasSemana: [5],
    diasMes: null,
    horaPrevista: "11:30",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "negocios-cripto",
    marca: "Negócios",
    nome: "Cripto",
    periodicidade: "dia_semana",
    diasSemana: [4],
    diasMes: null,
    horaPrevista: "11:30",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "record-benfica",
    marca: "Record",
    nome: "Benfica",
    periodicidade: "diaria",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "11:45",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "record-mundial-2022",
    marca: "Record",
    nome: "Mundial 2022",
    periodicidade: "diaria",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "12:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: false,
  },
  // Automático
  {
    id: "negocios-opiniao",
    marca: "Negócios",
    nome: "Opinião",
    periodicidade: "dias_uteis",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "12:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "maxima-fim-de-semana",
    marca: "Máxima",
    nome: "Fim de Semana",
    periodicidade: "dia_semana",
    diasSemana: [5],
    diasMes: null,
    horaPrevista: "12:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // horário em aberto no Excel ("12h ou 18h"); tolerância alargada até 18:00 + 1 h
  // Gerido
  {
    id: "negocios-valor-acrescentado",
    marca: "Negócios",
    nome: "Valor Acrescentado",
    periodicidade: "dia_semana",
    diasSemana: [1],
    diasMes: null,
    horaPrevista: "12:00",
    toleranciaMinutos: 420,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "flash-the-mag",
    marca: "Flash",
    nome: "The Mag",
    periodicidade: "dia_semana",
    diasSemana: [5],
    diasMes: null,
    horaPrevista: "13:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "record-euro",
    marca: "Record",
    nome: "Euro",
    periodicidade: "diaria",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "13:30",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: false,
  },
  // Automático
  {
    id: "negocios-ip",
    marca: "Negócios",
    nome: "IP",
    periodicidade: "dia_semana",
    diasSemana: [1],
    diasMes: null,
    horaPrevista: "14:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "negocios-a-economia-das-coisas",
    marca: "Negócios",
    nome: "A Economia das Coisas",
    periodicidade: "dia_semana",
    diasSemana: [5],
    diasMes: null,
    horaPrevista: "14:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "flash-moda-e-beleza",
    marca: "Flash",
    nome: "Moda e Beleza",
    periodicidade: "dias_uteis",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "15:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Automático
  {
    id: "negocios-tecnologia",
    marca: "Negócios",
    nome: "Tecnologia",
    periodicidade: "dias_uteis",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "15:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Automático
  {
    id: "negocios-weekend",
    marca: "Negócios",
    nome: "Weekend",
    periodicidade: "dia_semana",
    diasSemana: [6],
    diasMes: null,
    horaPrevista: "15:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Automático
  {
    id: "aq-maquina-geral",
    marca: "Aq Máquina",
    nome: "Geral",
    periodicidade: "dia_semana",
    diasSemana: [5],
    diasMes: null,
    horaPrevista: "15:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // estado por confirmar no Excel (coluna dizia "vazio")
  // 249
  {
    id: "sabado-gps",
    marca: "Sábado",
    nome: "GPS",
    periodicidade: "dia_semana",
    diasSemana: [4],
    diasMes: null,
    horaPrevista: "16:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: false,
  },
  // Automática
  {
    id: "cm-o-melhor-da-semana",
    marca: "CM",
    nome: "O Melhor da Semana",
    periodicidade: "dia_semana",
    diasSemana: [5],
    diasMes: null,
    horaPrevista: "16:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // estado por confirmar no Excel (coluna dizia "37")
  {
    id: "cm-indica",
    marca: "CM",
    nome: "Indica",
    periodicidade: "dia_semana",
    diasSemana: [3],
    diasMes: null,
    horaPrevista: "16:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: false,
  },
  // estado por confirmar no Excel (coluna dizia "37")
  {
    id: "record-indica",
    marca: "Record",
    nome: "Indica",
    periodicidade: "dia_semana",
    diasSemana: [5],
    diasMes: null,
    horaPrevista: "16:30",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: false,
  },
  // horário em aberto no Excel ("16h30 // 17h"); tolerância alargada até 17:00 + 1 h
  // Gerido
  {
    id: "must-must",
    marca: "Must",
    nome: "Must",
    periodicidade: "dia_semana",
    diasSemana: [3],
    diasMes: null,
    horaPrevista: "16:30",
    toleranciaMinutos: 90,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Automático
  {
    id: "sabado-as-mais-lidas",
    marca: "Sábado",
    nome: "As Mais Lidas",
    periodicidade: "dia_semana",
    diasSemana: [5],
    diasMes: null,
    horaPrevista: "16:30",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Automática
  {
    id: "cm-o-melhor-da-semana-2",
    marca: "CM",
    nome: "O Melhor da Semana",
    periodicidade: "dia_semana",
    diasSemana: [5],
    diasMes: null,
    horaPrevista: "17:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Automático
  {
    id: "negocios-lex",
    marca: "Negócios",
    nome: "Lex",
    periodicidade: "dia_semana",
    diasSemana: [4],
    diasMes: null,
    horaPrevista: "17:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "flash-life-style",
    marca: "Flash",
    nome: "Life & Style",
    periodicidade: "dias_uteis",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "17:30",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Automático
  {
    id: "negocios-dow-jones-fecho",
    marca: "Negócios",
    nome: "Dow Jones - Fecho",
    periodicidade: "dias_uteis",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "18:45",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: false,
  },
  // Automática
  {
    id: "cm-boa-tarde",
    marca: "CM",
    nome: "Boa Tarde",
    periodicidade: "diaria",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "19:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "record-jo2020",
    marca: "Record",
    nome: "JO2020",
    periodicidade: "diaria",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "19:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: false,
  },
  // Automático
  {
    id: "negocios-fecho",
    marca: "Negócios",
    nome: "Fecho",
    periodicidade: "dias_uteis",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "18:30",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "negocios-sua-semana",
    marca: "Negócios",
    nome: "Sua Semana",
    periodicidade: "dia_semana",
    diasSemana: [7],
    diasMes: null,
    horaPrevista: "20:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Gerido
  {
    id: "record-mundial-premium-2022",
    marca: "Record",
    nome: "Mundial Premium 2022",
    periodicidade: "diaria",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "21:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: false,
  },
  // Automático
  {
    id: "sabado-edicao-noite",
    marca: "Sábado",
    nome: "Edição Noite",
    periodicidade: "diaria",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "21:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
  // Excel diz "Mensal" sem dia nem hora
  // sem hora no Excel ("n/d")
  // Gerido
  {
    id: "negocios-assinantes-mensal",
    marca: "Negócios",
    nome: "Assinantes Mensal",
    periodicidade: "nao_agendada",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "00:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: false,
  },
  // sai a qualquer dia/hora
  // sem hora no Excel ("Sem horário")
  // Gerido
  {
    id: "record-dois-dedos-de-conversa",
    marca: "Record",
    nome: "Dois Dedos de Conversa",
    periodicidade: "nao_agendada",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "00:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: false,
  },
  // Excel diz "Mensal" sem dia nem hora
  // sem hora no Excel ("n/d")
  // Gerido
  {
    id: "maxima-mensal",
    marca: "Máxima",
    nome: "Mensal",
    periodicidade: "nao_agendada",
    diasSemana: null,
    diasMes: null,
    horaPrevista: "00:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: false,
  },
  // Gerido
  {
    id: "sabado-o-melhor-do-mes",
    marca: "Sábado",
    nome: "O Melhor do Mês",
    periodicidade: "dia_mes",
    diasSemana: null,
    diasMes: [1],
    horaPrevista: "12:00",
    toleranciaMinutos: 60,
    remetentes: [],
    padraoAssunto: "",
    ativa: true,
  },
];

export function newsletterPorId(id: string): Newsletter | undefined {
  return NEWSLETTERS.find((n) => n.id === id);
}

/** Uma newsletter está configurada quando já sabe reconhecer os seus emails. */
export function estaConfigurada(n: Newsletter): boolean {
  return n.remetentes.length > 0 && n.padraoAssunto.trim() !== "";
}
